services:
  - type: web
    name: financeiro-pessoal
    env: docker
    plan: starter
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
